name: 'Hugo Eureka Starters Deploy'
description: 'Deploy Hugo Eureka starters when the new version is released.'

branding:
  icon: folder-plus
  color: gray-dark

inputs:
  target_url:
    description: 'Target Repo URL'
    required: true
  target_username:
    description: 'Target Repo Username'
    required: true
  target_token:
    description: 'Target Token'
    required: true
  git_username:
    description: 'Git Username'
    required: true
  git_email:
    description: 'Git Email'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TARGET_URL: ${{ inputs.target_url }}
        INPUT_TARGET_USERNAME: ${{ inputs.target_username }}
        INPUT_TARGET_TOKEN: ${{ inputs.target_token }}
        INPUT_GIT_USERNAME: ${{ inputs.git_username }}
        INPUT_GIT_EMAIL: ${{ inputs.git_email }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
